### ISSUE TITLE
Can it actually be used without nix?

### ISSUE THREAD

**Issue by dudicoco** [simonfxr/nix-download#1]
Hi,

It seems that this tool needs an existing nix store.

Is it possible for the tool to install binaries from nix packages directly to the system without using nix at all?

**Comment by simonfxr** [comment]
Hi,

It does not require a local nix store, it consumes nix store paths as input and tries to download the path and all its dependencies to the local filesystem from any given remote binary cache (defaults tocache.nixos.org). 

This assumes that you already know the calculated store path, for this you need to have nix installed. You could use e.g. nix eval to get a store path: 

```sh
$ nix eval nixpkgs#hello.outPath
"/nix/store/041gszy7ccgmjv83lif6j6rzbqz5vjzg-hello-2.12.1"
```

And then you can pass this store path to `nix-download` on any other machine/container to download and run it.

Does this help?

**Comment by dudicoco** [comment]
Thanks @simonfxr.

I'm basically looking for a way to run nix packages binaries without installing nix, so I assume this tool won't be enough.
